/* Auto-generated by Chipr for BMI270. */
#include "bmi270.h"
#include "bmi270_regs.h"

int bmi270_read_reg(uint8_t reg, uint8_t *value) {
    return hal_bmi270_read(reg, value, 1);
}

int bmi270_write_reg(uint8_t reg, uint8_t value) {
    return hal_bmi270_write(reg, &value, 1);
}

int bmi270_init(void) {
    /* Call these in the order shown in Chipr's "Init" tab; each step there cites its datasheet page. */
    /* configure PWR_CTRL (0x7D) */
    return 0;
}
